version: '3'
volumes:
  static:

services:
  django:
    restart: always
    image: neurovault/neurovault_fs
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile_fs
    command: ./compose/django/prod_start
    ports: 
      - "8000:8000"
    volumes:
      - .:/code
      - ${NV_IMAGE_DATA}:/var/www/image_data/images
      - static:/var/www/static
    depends_on:
      - redis
    env_file:
      - ./.env

  redis:
    restart: always
    image: redis:6
    command: redis-server --appendonly yes

  worker:
    image: neurovault/neurovault
    command: celery -A neurovault.celery worker -Q default -n default@%h
    volumes:
      - .:/code
      - ${NV_IMAGE_DATA}:/var/www/image_data/images
    depends_on:
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./compose/nginx/certs:/etc/letsencrypt
      - ./compose/nginx/certs-data:/data/letsencrypt
      - static:/var/www/static
    volumes_from:
      - django
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
