# Generated by Django 4.2.4 on 2025-01-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticmap',
            name='cognitive_paradigm_name',
            field=models.CharField(blank=True, help_text='Name of your task', null=True, verbose_name='Cognitive Paradigm Other Name'),
        ),
        migrations.AddField(
            model_name='statisticmap',
            name='cognitive_paradigm_short_description',
            field=models.CharField(blank=True, help_text='Give your cognitive paradigm a short description', null=True, verbose_name='Cognitive Paradigm Short Description'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_cogatlas',
            field=models.ForeignKey(help_text="Task performed by the subjects in the scanner described using <a href='http://www.cognitiveatlas.org/' target='_blank'>Cognitive Atlas</a>. If no match, select 'None / Other'", null=True, on_delete=django.db.models.deletion.PROTECT, to='statmaps.cognitiveatlastask', verbose_name='Cognitive Atlas Paradigm'),
        ),
    ]
