# Generated by Django 4.2.4 on 2025-01-31 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0002_statisticmap_cognitive_paradigm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='preprint_DOI',
            field=models.CharField(blank=True, default=None, help_text='DOI of the corresponding preprint, if publication DOI is not yet available', max_length=200, null=True, verbose_name='Preprint DOI'),
        ),
        migrations.AlterField(
            model_name='image',
            name='figure',
            field=models.CharField(blank=True, help_text='Which figure in the corresponding paper was this map displayed in?', max_length=200, null=True, verbose_name='Manuscript figure'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_cogatlas',
            field=models.ForeignKey(help_text="Task performed by the subjects in the scanner described using <a href='http://www.cognitiveatlas.org/' target='_blank'>Cognitive Atlas</a>.", null=True, on_delete=django.db.models.deletion.PROTECT, to='statmaps.cognitiveatlastask', verbose_name='Cognitive Atlas Paradigm'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_description_url',
            field=models.URLField(blank=True, help_text='Link to a paper, poster, abstract describing in detail the task performed by the subject(s) in the scanner.', null=True, verbose_name='Description URL'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_name',
            field=models.CharField(blank=True, help_text='Name of your task (if it)', null=True, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_short_description',
            field=models.CharField(blank=True, help_text='Describe your task', null=True, verbose_name='Task Description'),
        ),
    ]
