# Generated by Django 4.2.4 on 2025-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0002_collection_preprint_doi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gender',
        ),
        migrations.AddField(
            model_name='image',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=200, null=True, verbose_name='Sex'),
        ),
    ]
