# Generated by Django 4.2.4 on 2025-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0003_remove_image_gender_image_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticmap',
            name='modality',
            field=models.CharField(choices=[('fMRI-BOLD', 'fMRI-BOLD'), ('fMRI-CBF', 'fMRI-CBF'), ('fMRI-CBV', 'fMRI-CBV'), ('Diffusion MRI', 'Diffusion MRI'), ('Structural MRI', 'Structural MRI'), ('PET FDG', 'PET FDG'), ('PET [15O]-water', 'PET [15O]-water'), ('PET other', 'PET other'), ('MEG', 'MEG'), ('EEG', 'EEG'), ('Other', 'Other')], db_index=True, help_text='Brain imaging procedure that was used to acquire the data.', max_length=200, verbose_name='Modality & Acquisition Type'),
        ),
        migrations.AddIndex(
            model_name='statisticmap',
            index=models.Index(fields=['modality', 'map_type'], name='statmaps_st_modalit_b6a96d_idx'),
        ),
    ]
