# Generated by Django 4.2.4 on 2025-02-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0003_collection_preprint_doi_alter_image_figure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('published', 'Yes'), ('submitted', 'Submitted'), ('in preparation', 'In Preparation'), ('not_intended', 'No')], help_text='Is this collection associated with a publication, or intended for publication?', null=True, verbose_name='Published?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='DOI',
            field=models.CharField(blank=True, default=None, help_text='Required if you want your maps to be archived in Stanford Digital Repository', max_length=200, null=True, unique=True, verbose_name='Publication DOI'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='preprint_DOI',
            field=models.CharField(blank=True, default=None, help_text='If there is not a publication DOI, please provide a preprint DOI', max_length=200, null=True, verbose_name='Preprint DOI'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='private',
            field=models.BooleanField(choices=[(False, 'Public'), (True, 'Private')], default=False, help_text='Public collections distributed under CC0 license. Private collections are not publicly indexed, but can be shared using a private URL.', verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='cognitive_paradigm_cogatlas',
            field=models.ForeignKey(help_text="Task performed by the subjects in the scanner described using <a href='http://www.cognitiveatlas.org/' target='_blank'>Cognitive Atlas</a>. If there's no match, select 'None / Other'. ", null=True, on_delete=django.db.models.deletion.PROTECT, to='statmaps.cognitiveatlastask', verbose_name='Cognitive Atlas Paradigm'),
        ),
    ]
