# Generated by Django 4.2.4 on 2025-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0004_alter_statisticmap_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecollectionitem',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='date modified'),
        ),
    ]
