# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statmaps', '0012_migrate_to_nidm3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='clusterLabelId',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='clusterSizeInResels',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='clusterSizeInVoxels',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='excursionSet',
            field=models.ForeignKey(blank=True, to='statmaps.ExcursionSet', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='pValueFWER',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='pValueUncorrected',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='qValueFDR',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clusterlabelmap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clusterlabelmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clusterlabelmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clusterlabelmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='clusterlabelmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='contrastWeights',
            field=models.ForeignKey(blank=True, to='statmaps.ContrastWeights', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='maskMap',
            field=models.ForeignKey(blank=True, to='statmaps.MaskMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='parameterEstimateMap',
            field=models.ForeignKey(blank=True, to='statmaps.ParameterEstimateMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastestimation',
            name='residualMeanSquaresMap',
            field=models.ForeignKey(blank=True, to='statmaps.ResidualMeanSquaresMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='contrastEstimation',
            field=models.ForeignKey(blank=True, to='statmaps.ContrastEstimation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='contrastName',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastmap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='contrastEstimation',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ContrastEstimation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contraststandarderrormap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='contrastName',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='statisticType',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#ZStatistic', b'Z'), (b'http://www.incf.org/ns/nidash/nidm#Statistic', b'Other'), (b'http://www.incf.org/ns/nidash/nidm#FStatistic', b'F'), (b'http://www.incf.org/ns/nidash/nidm#TStatistic', b'F')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contrastweights',
            name='value',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate1',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate2',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate3',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='dimensionsInVoxels',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='inWorldCoordinateSystem',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='numberOfDimensions',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='voxelSize',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='voxelToWorldMapping',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coordinatespace',
            name='voxelUnits',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='data',
            name='targetIntensity',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='designmatrix',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='designmatrix',
            name='image',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ProvImage'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='designmatrix',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='designmatrix',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='designmatrix',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='clusterLabelMap',
            field=models.ForeignKey(blank=True, to='statmaps.ClusterLabelMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='image',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ProvImage'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='inference',
            field=models.ForeignKey(blank=True, to='statmaps.Inference', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='maximumIntensityProjection',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='numberOfClusters',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='pValue',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='excursionset',
            name='underlayFile',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='clusterSizeInResels',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='clusterSizeInVoxels',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='pValueFWER',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='pValueUncorrected',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='qValueFDR',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extentthreshold',
            name='userSpecifiedThresholdType',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='pValueFWER',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='pValueUncorrected',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='qValueFDR',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='userSpecifiedThresholdType',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='heightthreshold',
            name='value',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='alternativeHypothesis',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='contrastMap',
            field=models.ForeignKey(blank=True, to='statmaps.ContrastMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='hasAlternativeHypothesis',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#TwoTailedTest', b'Two Tailed'), (b'http://www.incf.org/ns/nidash/nidm#OneTailedTest', b'One Tailed')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='reselsPerVoxelMap',
            field=models.ForeignKey(blank=True, to='statmaps.ReselsPerVoxelMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='inference',
            name='statisticMap',
            field=models.ForeignKey(blank=True, to='statmaps.StatisticMap', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='filename',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='format',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='map',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='hasMapHeader',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='modelParametersEstimation',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ModelParametersEstimation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='maskmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='data',
            field=models.ForeignKey(blank=True, to='statmaps.Data', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='designMatrix',
            field=models.ForeignKey(blank=True, to='statmaps.DesignMatrix', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='noiseModel',
            field=models.ForeignKey(blank=True, to='statmaps.NoiseModel', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='modelparametersestimation',
            name='withEstimationMethod',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#WeightedLeastSquares', b'WeightedLeastSquares'), (b'http://www.incf.org/ns/nidash/nidm#OrdinaryLeastSquares', b'OrdinaryLeastSquares'), (b'http://www.incf.org/ns/nidash/nidm#GeneralizedLeastSquares', b'GeneralizedLeastSquares'), (b'http://www.incf.org/ns/nidash/nidm#EstimationMethod', b'EstimatedMethod'), (b'http://www.incf.org/ns/nidash/nidm#RobustIterativelyReweighedLeastSquares', b'RobustIterativelyReweighedLeastSquares')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='dependenceSpatialModel',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#SpatiallyLocalModel', b'Spatiakky Local'), (b'http://www.incf.org/ns/nidash/nidm#SpatialModel', b'Spatial'), (b'http://www.incf.org/ns/nidash/nidm#SpatiallyRegularizedModel', b'SpatiallyRegularized'), (b'http://www.incf.org/ns/nidash/nidm#SpatiallyGlobalModel', b'Spatially Global')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='hasNoiseDependence',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#ArbitrarilyCorrelatedNoise', b'Arbitrarily Correlated'), (b'http://www.incf.org/ns/nidash/nidm#ExchangeableNoise', b'Exchangable'), (b'http://www.incf.org/ns/nidash/nidm#SeriallyCorrelatedNoise', b'Serially Correlated'), (b'http://www.incf.org/ns/nidash/nidm#CompoundSymmetricNoise', b'Compound Symmetric'), (b'http://www.incf.org/ns/nidash/nidm#IndependentNoise', b'Independent')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='hasNoiseDistribution',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'fsl:NonParametricSymmetricDistribution', b'Non-Parametric Symmetric'), (b'http://www.incf.org/ns/nidash/nidm#GaussianDistribution', b'Gaussian'), (b'http://www.incf.org/ns/nidash/nidm#NoiseDistribution', b'Noise'), (b'http://www.incf.org/ns/nidash/nidm#PoissonDistribution', b'Poisson'), (b'fsl:BinomialDistribution', b'Binomial'), (b'http://www.incf.org/ns/nidash/nidm#NonParametricDistribution', b'Non-Parametric')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='varianceSpatialModel',
            field=models.CharField(blank=True, max_length=200, null=True, choices=[(b'http://www.incf.org/ns/nidash/nidm#SpatiallyLocalModel', b'Spatially Local'), (b'http://www.incf.org/ns/nidash/nidm#SpatialModel', b'Spatial'), (b'http://www.incf.org/ns/nidash/nidm#SpatiallyRegularizedModel', b'Spatially Regularized'), (b'http://www.incf.org/ns/nidash/nidm#SpatiallyGlobalModel', b'Spatially Global')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='hasMapHeader',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='modelParameterEstimation',
            field=models.ForeignKey(blank=True, to='statmaps.ModelParametersEstimation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='parameterestimatemap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='cluster',
            field=models.ForeignKey(blank=True, to='statmaps.Cluster', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='equivalentZStatistic',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='pValueFWER',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='pValueUncorrected',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='qValueFDR',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='peak',
            name='value',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='provimage',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='provimage',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='provimage',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='provimage',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='modelParametersEstimation',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ModelParametersEstimation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reselspervoxelmap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='file',
            field=models.FileField(null=True, upload_to=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='modelParametersEstimation',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.ModelParametersEstimation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='residualmeansquaresmap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='expectedNumberOfClusters',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='expectedNumberOfVoxelsPerCluster',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='file',
            field=models.FileField(null=True, upload_to=b'hash_filestore', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='heightCriticalThresholdFDR05',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='heightCriticalThresholdFWE05',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='inCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='inference',
            field=models.ForeignKey(blank=True, to='statmaps.Inference', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='noiseFWHMInUnits',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='noiseFWHMInVoxels',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='reselSize',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='searchVolumeInResels',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='searchVolumeInUnits',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='searchVolumeInVoxels',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='searchVolumeReselsGeometry',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='smallestSignifClusterSizeInVoxelsFDR05',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='searchspacemap',
            name='smallestSignifClusterSizeInVoxelsFWE05',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='atCoordinateSpace',
            field=models.ForeignKey(related_name='+', blank=True, to='statmaps.CoordinateSpace', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='effectDegreesOfFreedom',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='errorDegreesOfFreedom',
            field=models.FloatField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='map',
            field=models.OneToOneField(null=True, blank=True, to='statmaps.Map'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='modelParametersEstimation',
            field=models.ForeignKey(blank=True, to='statmaps.ModelParametersEstimation', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='prov_URI',
            field=models.CharField(max_length=200, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='prov_label',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='prov_type',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statisticmap',
            name='sha512',
            field=models.CharField(max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
    ]
